- name: Setup SSH keys
  hosts: localhost
  become: true
  tasks:
    - name: Update all submodules
      tags:
        - submodules
        - nvim
      command:
        cmd: git submodule update --force --init --recursive --jobs 4
      changed_when: false

    - name: Install essentials
      tags:
        - essentials
      import_role:
        name: essentials

    - name: Decrypt and save ssh keys
      ignore_errors: true
      tags:
        - essentials
      import_role:
        name: ssh-keys

    - name: Run stow
      shell: "stow . --target {{ lookup('env', 'USER') }} --verbose=2"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'

