font_family FiraCode Nerd Font
font_size 10


include ./themes/mocha.conf


detect_urls no
copy_on_select clipboard
strip_trailing_spaces smart
select_by_word_characters ${}/&@_.
focus_follows_mouse yes
mouse_map right press grabbed,ungrabbed no-op
mouse_map right click grabbed,ungrabbed paste_from_clipboard
allow_hyperlinks no

