- name: Ensure temporary directory exists
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: '0700'
  ignore_errors: true
  tags:
    - essentials

- name: Copy the zip file to the remote system
  ansible.builtin.copy:
    src: ssh_keys.zip
    dest: /tmp/ssh_keys.zip
  changed_when: false
  ignore_errors: true
  tags:
    - essentials

- name: Extract the decrypted zip file
  ansible.builtin.unarchive:
    src: /tmp/ssh_keys.zip
    dest: "{{ ssh_dir }}"
    remote_src: true
  ignore_errors: true
  tags:
    - essentials

- name: Remove the zip file after extraction
  ansible.builtin.file:
    path: /tmp/ssh_keys.zip
    state: absent
  changed_when: false
  ignore_errors: true
  tags:
    - essentials
