- name: Install essensial apps
  community.general.pacman:
    name:
      - neovim
      - man-db
      - unzip
      - zip
      - zsh
      - stow
      - wget
      - git
      - eza
      - jq
      - zoxide
      - tmux
      - base-devel ## for yay
    state: present
    update_cache: true

- name: Install programming things
  community.general.pacman:
    name:
      - python
      - npm
      - go
      - lazygit
      - make
      - lazygit
    state: present
    update_cache: true

- name: Install Optionals
  community.general.pacman:
    name:
      - ansible-core
      - openssh
      - bat
      - btop
      - net-tools
    state: present
    update_cache: true

- name: Ensure YAY exists
  ansible.builtin.import_tasks:
    file: install-yay.yml

- name: Install essensial apps AUR
  yay:
    name:
      - fzf-git
    state: present
