- name: Ensure temporary directory exists
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: '0700'

- name: Copy the zip file to the remote system
  ansible.builtin.copy:
    src: ssh_keys.zip
    dest: /tmp/ssh_keys.zip

- name: Extract the decrypted zip file
  ansible.builtin.unarchive:
    src: /tmp/ssh_keys.zip
    dest: "{{ ssh_dir }}"
    remote_src: yes

