
- name: Ensure sshd service is enabled and started
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: started

- name: Configure PermitRootLogin in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin.*'
    line: 'PermitRootLogin yes'
    state: present
  notify: Restart SSH

  # Handlers
- name: Restart SSH
  ansible.builtin.systemd:
    name: sshd
    state: restarted
