general.import = [
    "./mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true
dynamic_padding = true 
padding = { x = 0, y = 0 }


[font]
size = 14.0
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"

[keyboard]
bindings = [
    { key = "Enter", mods = "Control|Shift", chars = "\u001b[13;6u" },
]

