- name: Install essensial apps
  community.general.pacman:
    name:
      - neovim
      - man-db
      - unzip
      - zip
      - zsh
      - stow
      - wget
      - git
      - eza
      - jq
      - zoxide
      - tmux
      - ripgrep

    state: present
    update_cache: true


- name: Ensure YAY exists
  ansible.builtin.import_tasks:
    file: install-yay.yml

- name: Install essensial apps AUR
  yay:
    name:
      - sesh-bin
      - fzf-git
    state: present
