- name: Update the system package database
  community.general.pacman:
    update_cache: true
  become: true

- name: Install base-devel and git if not already installed
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present
  become: true

- name: Check if yay is already installed
  ansible.builtin.command:
    cmd: yay --version
  register: yay_check
  ignore_errors: true
  changed_when: false

- name: a
  ansible.builtin.debug:
    - "{{ ansible_env.HOME }}"
	

- name: Clone the yay repository into the home directory if yay is not installed
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ ansible_env.HOME }}/yay"
    clone: true
    update: false
  when: yay_check.rc != 0
  become: false  # Run as the connected user

- name: Build and install yay from the user's home directory
  ansible.builtin.command:
    cmd: makepkg -si --noconfirm
    chdir: "{{ ansible_env.HOME }}/yay"
  args:
    creates: /usr/bin/yay
  when: yay_check.rc != 0
  become: false  # Run as the connected user

- name: Remove the yay repository after installation
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/yay"
    state: absent
  when: yay_check.rc != 0
