- name: Install essntial apps
  ansible.builtin.import_tasks:
    file: ./arch.yml
  when: ansible_distribution == "Archlinux"
  remote_user: true
  tags:
    - essentials

- name: Set default shell for a user
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"  # Replace with the actual username
    shell: /bin/zsh  # Replace with the desired shell
  tags:
    - essentials

- name: Update all submodules

  ansible.builtin.command:
    cmd: git submodule update --force --init --recursive --jobs 4
  tags:
    - essentials
    - submodules
  changed_when: false
