- name: Install essensial apps
  community.general.pacman:
    name:
      - lazygit
      - neovim
      - man-db
      - unzip
      - zip
      - zsh
      - openssh
      - stow
      - bat
      - ansible-core
      - wget
      - btop
      - git
      - python
      - eza
      - npm
      - go
      - zoxide
      - tmux
      # - fzf-git
    state: present
